MainClassRefactor
Star-Academy/Winter1400-Co_Op pull request #1
Opened 2022-02-07 05:42 UTC by mohammadKhalafi

refactoring...

2022-02-07 06:57 UTC, ARB1380 commented
and function replace with retain all

2022-02-07 07:18 UTC, ARB1380 commented
the funvtion getHashSetOfQueries : the loop can be put in another method for example :
void addHashsets (ArrayList hashsets) an dput the loop in it

2022-02-07 07:39 UTC, mohammadKhalafi commented
thank you for your comments alireza!

2022-02-07 12:11 UTC, MKasaei00 requested changes

2022-02-07 12:11 UTC, MKasaei00 commented on src/Main.java
> +        for (String query : mainQuery.split(" ")){
<div dir='rtl' >
رشته ای که به عنوان جداکننده انتخاب کردین رو توی کد تکرار و استفاده نکنید و به عنوان مقدار ثابت در اول کلاس تعیین بشه
</div>

2022-02-07 12:11 UTC, MKasaei00 commented on src/Main.java
> +class queries{
هر کلاس در یک فایل جدا باشه

2022-02-07 12:11 UTC, MKasaei00 commented on src/Main.java
> +    public static void main(String[] args) {
<div dir='rtl' >
کلاس Main رو خالی کنید و همه توابع به جز main رو ریفکتور کنید و با طراحی مناسب جای خوبی براشون پیدا کنید.
</div>

2022-02-07 12:11 UTC, MKasaei00 commented on src/Main.java
> +    public static void main(String[] args) {
مثلا یه کلاس برای ارتباط با کاربر بزنید و ورودی گرفتن رو اون کلاس انجام بده

2022-02-08 06:02 UTC, MKasaei00 commented on src/FileReader.java
> +    public  HashMap<String, HashSet<Integer>> fillIndexes() {
ورودی file  اصلاح بشه  لطفا

2022-02-08 07:05 UTC, MKasaei00 approved these changes

2022-02-08 07:27 UTC, merged