Stemmer clean code
Star-Academy/Winter1400-Co_Op pull request #2
Opened 2022-02-07 06:21 UTC by BozorgmehrZia

2022-02-07 07:19 UTC, mohammadKhalafi commented
salam
in changeSuffixFinishSecondStep method "return true" is duplicated code, and you can use default for your switch case to return false and return true at the end of method.

2022-02-07 07:56 UTC, ARB1380 commented
salam
in function checkDoubleConsonantSequence the second thing in the if part( char[index] != char[index - 1] can be put in another method and just call in this if

2022-02-07 07:59 UTC, BozorgmehrZia commented
> salam in function checkDoubleConsonantSequence the second thing in the if part( char[index] != char[index - 1] can be put in another method and just call in this if
ino bishtar tozih midi

2022-02-07 08:00 UTC, ARB1380 commented
salam
in function constantVowelConstantSequence the return part can be put in another function

2022-02-07 08:01 UTC, ARB1380 commented
> > salam in function checkDoubleConsonantSequence the second thing in the if part( char[index] != char[index - 1] can be put in another method and just call in this if
> > ino bishtar tozih midi

ye tabe ye khati masalan mese hamoon isContant ke boolean bar migardoone bashe in made nazaram bood

2022-02-07 08:04 UTC, mohammadKhalafi commented
in method checkConsonantForI the logic created by "if,else" is !(a ^ b)

2022-02-07 08:18 UTC, mohammadKhalafi commented
تست فارسی

2022-02-07 12:01 UTC, MKasaei00 requested changes

2022-02-07 12:01 UTC, MKasaei00 commented on src/Stemmer.java
> +    private boolean changeSuffixFinishFirstStep(char ch){
<div dir='rtl' >
کامنت‌های توابع رو به فرمت مشخص javadoc بنویسید
</div>

2022-02-08 06:03 UTC, MKasaei00 approved these changes

2022-02-08 06:08 UTC, merged