change of file reader class
Star-Academy/Winter1400-Co_Op pull request #3
Opened 2022-02-07 06:22 UTC by ARB1380

document process class is on brach master :))) you only file reader can be seen.

2022-02-07 11:54 UTC, MKasaei00 requested changes
خسته نباشید
چند تا کامنت گذاشتم

2022-02-07 11:54 UTC, MKasaei00 commented on src/FileReader.java
> +        assert files != null;
<div dir='rtl' >

گذاشتن assert درکد خوب نیست اگر ممکنه خطایی رخ بده استثنا پرتاب بشه
</div>

2022-02-07 11:54 UTC, MKasaei00 commented on src/FileReader.java
> +            return;
<div dir='rtl' >
خوبه نتیجه انجام شدن یا نشدن عملیات به توابع بیرونی هم برسه و از خارج تابع بدونیم که آیا عملیات انجام شده یا نه
</div>

2022-02-07 11:54 UTC, MKasaei00 commented on src/FileReader.java
> +        File file = new File("files");
<div dir='rtl' >
اسم فایل نباید توی کد نهایی مستقیم نوشته بشه 

یه متغییر توی تابع اصلی تعریف کنید و بعد در اختیار کلاس قرار بدید تا از اونجا بخونه
طراحی کلاس خاص منظوره نباشه
</div>

2022-02-07 11:54 UTC, MKasaei00 commented on src/FileReader.java
> +            return new String(Files.readAllBytes(Path.of(fileToRead.getAbsolutePath())));
<div dir='rtl' >
بهتره تا حد منطقی از متغییرهای میانی استفاده کنید و نوشتن یک خط کد خیلی طولانی کار درستی نیست
</div>

2022-02-07 11:54 UTC, MKasaei00 commented on src/FileReader.java
> +
<div dir='rtl' >
تمیزی ظاهری کد و خط های خالی رو هم استاندارد کنید
</div>

2022-02-08 06:03 UTC, MKasaei00 commented on src/FileReader.java
> +            return new String(Files.readAllBytes(Path.of(fileToRead.getAbsolutePath())));
این مورد لطفا اصلاح بشه

2022-02-08 06:50 UTC, ARB1380 commented on src/FileReader.java
> +            return new String(Files.readAllBytes(Path.of(fileToRead.getAbsolutePath())));
انجام شد

2022-02-08 07:04 UTC, MKasaei00 approved these changes

2022-02-08 07:05 UTC, MKasaei00 approved these changes

2022-02-08 07:09 UTC, merged