initialize project
Star-Academy/Winter1400-Co_Op pull request #7
Opened 2022-02-16 13:56 UTC by mohammadKhalafi

2022-02-16 13:58 UTC, mohammadKhalafi commented on searchProject_csharp/SampleLibrary/SampleLibrary/FileReader.cs
> +
اینتر اضافه حذف شود.

2022-02-16 14:04 UTC, mohammadKhalafi commented on searchProject_csharp/SampleLibrary/SampleLibrary/DocumentProcessor.cs
> +        private string data;
بر اساس قرارداد سی شارپ _data نوشته شود.

2022-02-17 10:55 UTC, RAAvenger requested changes
سلام بچه ها خسته نباشید
کداتون خوبن ولی یکم جای کار دارن
:)

2022-02-17 10:55 UTC, RAAvenger commented on searchProject_csharp/.gitignore.txt
> +
گیت ایگنور چرا پسوند txt داره؟

2022-02-17 10:55 UTC, RAAvenger commented on searchProject_csharp/SampleLibrary/SampleLibrary/Class1.cs
> +}
این چیه؟

2022-02-17 10:55 UTC, RAAvenger commented on searchProject_csharp/SampleLibrary/SampleLibrary/Controller.cs
> +            _dictionary = fileReader.GetIndexes();
چرا اول اسم  دیکشنری اندرلاین گذاشتین؟

2022-02-17 10:55 UTC, RAAvenger commented on searchProject_csharp/SampleLibrary/SampleLibrary/Controller.cs
> +        private Dictionary<string, HashSet<int>> _dictionary;
readonly

2022-02-17 10:55 UTC, RAAvenger commented on searchProject_csharp/SampleLibrary/SampleLibrary/Controller.cs
> +        public Queries Query{set; get;}
چرا setter داره؟

2022-02-17 10:55 UTC, RAAvenger commented on searchProject_csharp/SampleLibrary/SampleLibrary/Queries.cs
> +            }
متدش کنید و متد رو توی کانستراکتور صدا بزنید

2022-02-17 10:55 UTC, RAAvenger commented on searchProject_csharp/SampleLibrary/SampleLibrary/FileReader.cs
> +        private Dictionary<string,HashSet<int>> indexes = new Dictionary<string, HashSet<int>>();
readonly

2022-02-17 10:55 UTC, RAAvenger commented on searchProject_csharp/SampleLibrary/SampleLibrary/FileReader.cs
> +            DirectoryInfo di = new DirectoryInfo(_path);
var di = ne...

اسامی متغییرا رو هم با معنی انتخاب کنید، مهم نیست طولانی بشن.

2022-02-17 10:55 UTC, RAAvenger commented on searchProject_csharp/SampleLibrary/SampleLibrary/FileReader.cs
> +        public Boolean readDataFromFile(string path,string name){
ویژوال استودیو یه اکستنشن به نام codeMaid داره که پیشنهاد میکنم استفاده کنید.

2022-02-17 10:55 UTC, RAAvenger commented on searchProject_csharp/SampleLibrary/SampleLibrary/FileReader.cs
> +        public Boolean readDataFromFile(string path,string name){
حواستون به [Primitive Obsession](https://refactoring.guru/smells/primitive-obsession) هم باشه

2022-02-17 10:55 UTC, RAAvenger commented on searchProject_csharp/SampleLibrary/SampleLibrary/FileReader.cs
> +        }
اینجا به نظر single resoinsibility یکم خدشه دار شده.

2022-02-17 10:55 UTC, RAAvenger commented on searchProject_csharp/SampleLibrary/SampleLibrary/FileReader.cs
> +        }
از این استفاده نکردین

2022-02-17 10:55 UTC, RAAvenger commented on searchProject_csharp/SampleLibrary/SampleLibrary/FileReader.cs
> +        }
کدای بلا استفاده رو پاک کنید

2022-02-17 10:55 UTC, RAAvenger commented on searchProject_csharp/SampleLibrary/SampleLibrary.Test/ControllerTest.cs
> +        controller = new Controller
چرا از mock استفاده نکردین؟

2022-02-17 10:55 UTC, RAAvenger commented on searchProject_csharp/SampleLibrary/SampleLibrary/FileReader.cs
> +    public class FileReader : IFileReader
چرا متدای پابلیکی دارید که توی اینترفیس نیستن؟

2022-02-17 10:55 UTC, RAAvenger commented on searchProject_csharp/SampleLibrary/SampleLibrary/HashSetOperators.cs
> +    }
از استاتیکای اینجوری کلا استفاده نکنید

2022-02-17 10:55 UTC, RAAvenger commented on searchProject_csharp/SampleLibrary/SampleLibrary/DummyFileReader.cs
> +}
اگه توی تستاتون لازمه پس توی تستا از moq استفاده کنید و این رو هم پاک کنید.

2022-02-17 10:55 UTC, RAAvenger commented on searchProject_csharp/SampleLibrary/SampleLibrary/DocumentProcessor.cs
> +        private string data;
readonly

2022-02-17 10:55 UTC, RAAvenger commented on searchProject_csharp/SampleLibrary/SampleLibrary/DocumentProcessor.cs
> +            return toStemSplit();
به جای تعریف این توابع به صورت void جوری تعریفشون کنید که مقدار برگردونن.

2022-02-17 10:55 UTC, RAAvenger commented on searchProject_csharp/SampleLibrary/SampleLibrary/DocumentProcessor.cs
> +        }
خود c# داره.

2022-02-17 10:55 UTC, RAAvenger commented on searchProject_csharp/SampleLibrary/SampleLibrary/DocumentProcessor.cs
> +            if(data == null)
یه بار توی کانستراکتور به ازای string.IsNullOrWhiteSpace(data) اکسپشن بدید که هزارجا بررسی نکنید.

2022-02-17 10:55 UTC, RAAvenger commented on searchProject_csharp/SampleLibrary/SampleLibrary/DocumentProcessor.cs
> +            return data.Split(" ");
اوکیه که اینو متد کردید ولی اگر فقط یه جا استفاده شده میتونستید متدش نکنید.

2022-02-17 10:55 UTC, RAAvenger commented on searchProject_csharp/SampleLibrary/SampleLibrary/Controller.cs
> +                        fileIDsMatchMinusQueries);
توی کانستراکتور یه Operators بگیرید و روش کار کنید.

2022-02-17 10:55 UTC, RAAvenger commented on searchProject_csharp/SampleLibrary/SampleLibrary/Controller.cs
> +                        fileIDsMatchMinusQueries);
یا یکی بسازید.

2022-02-17 10:55 UTC, RAAvenger commented on searchProject_csharp/SampleLibrary/SampleLibrary.Test/QueriesTest.cs
> +        Queries queries = new Queries
جهت تمیزی میتونید یه type داشته باشید برای این queries و یه query processor که string بخونه و اون تایپه رو بسازه.
ولی این به هر حال اوکیه.

2022-02-17 10:55 UTC, RAAvenger commented on searchProject_csharp/SampleLibrary/SampleLibrary.Test/HashSetOperatorsTest.cs
> +    private HashSet<int> _set1, _set2, _set3, _set4;
readonly
اگر هم بخواید میتونید static readonly کنید و جلوی خودشون مقدار بدید.

2022-02-17 10:55 UTC, RAAvenger commented on searchProject_csharp/SampleLibrary/SampleLibrary/HashSetOperators.cs
> +    }
https://deviq.com/antipatterns/static-cling

2022-02-17 10:55 UTC, RAAvenger commented on searchProject_csharp/SampleLibrary/SampleLibrary.Test/FileReaderAndDocumentProcesorTest.cs
> +        @"f:/moh/Winter1400-Co_Op/searchProject_csharp/files";
?????????????????????????
چرا مسیر مطلق دادید؟
اینا رو هم بذارید تو ریپو و مسیر نسبی بدین.

2022-02-17 10:55 UTC, RAAvenger commented on searchProject_csharp/SampleLibrary/SampleLibrary.Test/FileReaderAndDocumentProcesorTest.cs
> +{
اصلا سینگل رسپانسبل نیست.

2022-02-17 10:55 UTC, RAAvenger commented on searchProject_csharp/SampleLibrary/SampleLibrary.Test/FileReaderAndDocumentProcesorTest.cs
> +            Assert.Equal(expected[i],result[i]);
از fluent assertion استفاده کنید و یه جا دوتا ارایه رو مقایسه کنید.

2022-02-17 10:55 UTC, RAAvenger commented on searchProject_csharp/SampleLibrary/SampleLibrary.Test/ControllerTest.cs
> +    Controller controller;
readonly

2022-02-17 11:54 UTC, MKasaei00 requested changes
خسته نباشین
علاوه بر نکاتی که رضا اشاره کرد به نظرم بعضی موارد رو هم بررسی کنین خوب باشه

2022-02-17 11:54 UTC, MKasaei00 commented on searchProject_csharp/SampleLibrary/SampleLibrary.Test/ControllerTest.cs
> +    Controller controller;
access modifier : public or private

2022-02-17 11:54 UTC, MKasaei00 commented on searchProject_csharp/SampleLibrary/SampleLibrary.Test/ControllerTest.cs
> +public void Test1(){
میزان جلوآمدگی کد رو بررسی مرتب کنید با بقیه‌ی قسمت‌ها

2022-02-17 11:54 UTC, MKasaei00 commented on searchProject_csharp/SampleLibrary/SampleLibrary.Test/FileReaderAndDocumentProcesorTest.cs
> +        @"f:/moh/Winter1400-Co_Op/searchProject_csharp/files";
فقط فایل‌هایی متنی که وابسته به تست هست توی ریپو باشه

2022-02-17 11:54 UTC, MKasaei00 commented on searchProject_csharp/SampleLibrary/SampleLibrary.Test/FileReaderAndDocumentProcesorTest.cs
> +        Assert.True(fileReader.readDataFromFile(
long line : 
از متغییر های میانی استفاده بشه که کدها رو راحت تر متوجه بشیم

2022-02-17 11:54 UTC, MKasaei00 commented on searchProject_csharp/SampleLibrary/SampleLibrary.Test/QueriesTest.cs
> +public class QueriesTest
تست ها معمولا با تعداد زیاد نوشته می‌شن
و در هر تست یه حالت خاص رو امتحان می کنیم و بعد از نوشتن تست برای هر بخش به صورت جدا ،  یه تست پیچیده می‌نویسیم که همه ی حالت‌های خاص رو هم پوشش بده
توی این کد فقط یک تست کامل نوشته شده.

2022-02-17 11:54 UTC, MKasaei00 commented on searchProject_csharp/SampleLibrary/SampleLibrary/Controller.cs
> +         (HashSet<int>zeroHashSet, HashSet<int>plusHashSet)
در خیلی از بخش های کدتون spacing و code reformat رعایت نشده.
مثلا بین نام آرگوما و نوع اون فاصله وجود نداره

2022-02-17 11:54 UTC, MKasaei00 commented on searchProject_csharp/SampleLibrary/SampleLibrary/DocumentProcessor.cs
> +        private void toLowerCase(){
استفاده از توابع void زیاد خوب نیست. بهتره با خروجی توابع نتایج و مراحل برنامه طی بشه

2022-02-17 11:54 UTC, MKasaei00 commented on searchProject_csharp/SampleLibrary/SampleLibrary/DocumentProcessor.cs
> +
extra enter

2022-02-17 11:54 UTC, MKasaei00 commented on searchProject_csharp/SampleLibrary/SampleLibrary/DocumentProcessor.cs
> +            string[] splittedData = splitData();
var

2022-02-17 11:54 UTC, MKasaei00 commented on searchProject_csharp/SampleLibrary/SampleLibrary/DocumentProcessor.cs
> +            for(int i = 0; i < splittedData.Length; i++){
var

2022-02-17 11:54 UTC, MKasaei00 commented on searchProject_csharp/SampleLibrary/SampleLibrary/FileReader.cs
> +            DirectoryInfo di = new DirectoryInfo(_path);
var

2022-02-17 11:54 UTC, MKasaei00 commented on searchProject_csharp/SampleLibrary/SampleLibrary/FileReader.cs
> +
extra line

2022-02-17 11:54 UTC, MKasaei00 commented on searchProject_csharp/SampleLibrary/SampleLibrary/FileReader.cs
> +            string[] words = processDataAndGiveWords(data);
var 
و خیلی جاهای دیگه

2022-02-17 11:54 UTC, MKasaei00 commented on searchProject_csharp/SampleLibrary/SampleLibrary/IFileReader.cs
> +         public Dictionary<string, HashSet<int>> GetIndexes();
Single responsibility
وظیفه‌ی fileReader ایندکس کردن نیست.

2022-02-17 11:54 UTC, MKasaei00 commented on searchProject_csharp/SampleLibrary/SampleLibrary.Test/HashSetOperatorsTest.cs
> +        var expected = new HashSet<int>();
اسم تست‌ها توصیفی تر باشه
در صورتی که طولانی بشه هم اصلا مهم نیست
قرار نیست صدا بزنیم این توابع رو
موقعی که خطا می خوره باید حس بگیریم که چه  قسمتی مشکل داره

2022-02-17 11:54 UTC, MKasaei00 commented on searchProject_csharp/SampleLibrary/SampleLibrary.Test/ControllerTest.cs
> +    public void Test2(){
meaningful test name

2022-02-19 06:25 UTC, ARB1380 commented on searchProject_csharp/SampleLibrary/SampleLibrary/Controller.cs
> +            _dictionary = fileReader.GetIndexes();
چون توی داک ها بود که فیلد پرایوت اول اسمش اندرلاین میاد

2022-02-19 06:29 UTC, BozorgmehrZia commented on searchProject_csharp/SampleLibrary/SampleLibrary/Controller.cs
> +        public Queries Query{set; get;}
به این دلیل که کوئری های متفاوت می گیریم در constructor آن را دریافت نمی کنیم و با setter این کار را انجام می دهیم.

2022-02-19 07:03 UTC, ARB1380 commented on searchProject_csharp/SampleLibrary/SampleLibrary.Test/QueriesTest.cs
> +        Queries queries = new Queries
میشه یکم اینو بیشتر توضیح بدید؟  متوجه نشدیم یعنی به جای کانستراکتور یک کلاس جدا داشته باشیم؟

2022-02-19 09:02 UTC, ARB1380 commented on searchProject_csharp/SampleLibrary/SampleLibrary/DocumentProcessor.cs
> +        private string data;
در چند تابع نیاز است که data تغییر پیدا کند بنابراین  نمیتوانیم read only بزاریم

2022-02-19 09:06 UTC, ARB1380 commented on searchProject_csharp/SampleLibrary/SampleLibrary/DocumentProcessor.cs
> +            return toStemSplit();
دیتا را به عنوان فیلد گذاشتیم و  این توابع تغییرات را در این فیلد ذخیره میکند.

2022-02-20 14:10 UTC, MKasaei00 requested changes

2022-02-20 14:10 UTC, MKasaei00 commented on searchProject_csharp/.gitignore.txt
> +
لطفا اینو اصلاح کنین

2022-02-20 14:10 UTC, MKasaei00 commented on searchProject_csharp/SampleLibrary/SampleLibrary.Test/FileReaderTest.cs
> +         string[] words = documentProcessor.getNormalizedWords();
var

2022-02-20 14:10 UTC, MKasaei00 commented on searchProject_csharp/SampleLibrary/SampleLibrary.Test/FileReaderTest.cs
> +        Dictionary<string,string> data =  controller.ReadData(foldersPath);
var

2022-02-20 14:10 UTC, MKasaei00 commented on searchProject_csharp/SampleLibrary/SampleLibrary.Test/FileReaderTest.cs
> +        Dictionary<string,string> data =  controller.ReadData(foldersPath);
و بقیه‌ی جاها لطفا

2022-02-20 14:10 UTC, MKasaei00 commented on searchProject_csharp/SampleLibrary/SampleLibrary.Test/QueriesTest.cs
> +        expectedMinusQueries.Add("six");
در مورد مقداردهی inline لیست ها در c# بخونید و استفاده کنین

2022-02-20 14:10 UTC, MKasaei00 commented on searchProject_csharp/SampleLibrary/SampleLibrary/ContentSaver.cs
> +                HashSet<int> fileIds = ComputeIfAbsent(words[i]);
var

2022-02-20 14:10 UTC, MKasaei00 commented on searchProject_csharp/SampleLibrary/SampleLibrary/Controller.cs
> +        catch(Exception)
این کار خوب نیست و باعث میشه تمام اشکالات کد به صورت نال خنثی بشه
خوبه که یک فرزند از نوع exception توی کد بسازین و موقعی که یه مشکل خاص می خورین  با توجه به اون مشکل خاص استثنا پرتاب کنین

و اینجا فقط و فقط یک یا چند استثنا رو هندل کنین

2022-02-20 14:10 UTC, MKasaei00 commented on searchProject_csharp/SampleLibrary/SampleLibrary/Controller.cs
> +        catch(Exception)
با این کدی که الان نوشتین هر اتفاق خواسته یا ناخواسته‌ای که رخ بده متوجه نمیشید

2022-02-20 14:10 UTC, MKasaei00 commented on searchProject_csharp/SampleLibrary/SampleLibrary/Controller.cs
> +        catch(Exception)
سوالی در این مورد بود  ازمن بپرسید

2022-02-20 14:10 UTC, MKasaei00 commented on searchProject_csharp/SampleLibrary/SampleLibrary/DocumentProcessor.cs
> +            if(data == null)
سینتکس ?? رو توی سی‌شارپ ببینید جالبه

2022-02-20 14:10 UTC, MKasaei00 commented on searchProject_csharp/SampleLibrary/SampleLibrary/DocumentProcessor.cs
> +            for(int i = 0; i < splittedData.Length; i++)
جاهایی  که میشه از linq استفاده کنید بهتره که کد یکنواخت و تمیزتر بشه

2022-02-21 13:12 UTC, RAAvenger commented on searchProject_csharp/SampleLibrary/SampleLibrary/Queries.cs
> +        public List<string> minusQueries {set; get;} = new ();
نیازی به setter نیست

2022-02-21 13:12 UTC, RAAvenger commented on searchProject_csharp/SampleLibrary/SampleLibrary/QueryManager.cs
> +        }
نیازی هست؟

2022-02-21 13:12 UTC, RAAvenger commented on searchProject_csharp/SampleLibrary/SampleLibrary/DocumentProcessor.cs
> +            return toStemSplit();
اصلاح کنید

2022-02-21 13:13 UTC, RAAvenger commented on searchProject_csharp/SampleLibrary/SampleLibrary.Test/QueriesTest.cs
> +        Queries queries = new Queries
دوتا کلاس میتونید داشته باشید
یکی که برای پردازش متن و تولید کوئری باشه و یکی که همون کوئری هست.

2022-02-22 07:09 UTC, MKasaei00 approved these changes

2022-02-22 07:57 UTC, BozorgmehrZia commented on searchProject_csharp/SampleLibrary/SampleLibrary.Test/ControllerTest.cs
> +        controller = new Controller
چون می خواهیم controller را تست کنیم

2022-02-22 08:09 UTC, ARB1380 commented on searchProject_csharp/SampleLibrary/SampleLibrary/FileReader.cs
> +        private Dictionary<string,HashSet<int>> indexes = new Dictionary<string, HashSet<int>>();
++

2022-02-22 08:10 UTC, ARB1380 commented on searchProject_csharp/SampleLibrary/SampleLibrary/FileReader.cs
> +        }
++

2022-02-22 08:11 UTC, ARB1380 commented on searchProject_csharp/SampleLibrary/SampleLibrary/FileReader.cs
> +    public class FileReader : IFileReader
برای تست کلاس

2022-02-22 08:12 UTC, ARB1380 commented on searchProject_csharp/SampleLibrary/SampleLibrary/HashSetOperators.cs
> +    }
++

2022-02-22 08:14 UTC, ARB1380 commented on searchProject_csharp/SampleLibrary/SampleLibrary/DummyFileReader.cs
> +}
++

2022-02-22 08:14 UTC, ARB1380 commented on searchProject_csharp/SampleLibrary/SampleLibrary/DocumentProcessor.cs
> +        private string data;
++

2022-02-22 08:14 UTC, ARB1380 commented on searchProject_csharp/SampleLibrary/SampleLibrary/DocumentProcessor.cs
> +            return toStemSplit();
++

2022-02-22 08:15 UTC, ARB1380 commented on searchProject_csharp/SampleLibrary/SampleLibrary/DocumentProcessor.cs
> +        }
++

2022-02-22 08:15 UTC, ARB1380 commented on searchProject_csharp/SampleLibrary/SampleLibrary/DocumentProcessor.cs
> +            if(data == null)
++

2022-02-22 08:16 UTC, ARB1380 commented on searchProject_csharp/SampleLibrary/SampleLibrary/DocumentProcessor.cs
> +            return data.Split(" ");
++

2022-02-22 08:17 UTC, ARB1380 commented on searchProject_csharp/SampleLibrary/SampleLibrary/Controller.cs
> +                        fileIDsMatchMinusQueries);
++

2022-02-22 08:32 UTC, ARB1380 commented on searchProject_csharp/SampleLibrary/SampleLibrary.Test/QueriesTest.cs
> +        Queries queries = new Queries
++

2022-02-22 08:33 UTC, ARB1380 commented on searchProject_csharp/SampleLibrary/SampleLibrary.Test/HashSetOperatorsTest.cs
> +    private HashSet<int> _set1, _set2, _set3, _set4;
++

2022-02-22 08:33 UTC, ARB1380 commented on searchProject_csharp/SampleLibrary/SampleLibrary.Test/FileReaderAndDocumentProcesorTest.cs
> +        @"f:/moh/Winter1400-Co_Op/searchProject_csharp/files";
++

2022-02-22 08:33 UTC, ARB1380 commented on searchProject_csharp/SampleLibrary/SampleLibrary.Test/FileReaderAndDocumentProcesorTest.cs
> +{
++

2022-02-22 08:43 UTC, ARB1380 commented on searchProject_csharp/SampleLibrary/SampleLibrary.Test/FileReaderAndDocumentProcesorTest.cs
> +            Assert.Equal(expected[i],result[i]);
++

2022-02-22 08:45 UTC, ARB1380 commented on searchProject_csharp/SampleLibrary/SampleLibrary.Test/ControllerTest.cs
> +    Controller controller;
++

2022-02-22 08:47 UTC, ARB1380 commented on searchProject_csharp/SampleLibrary/SampleLibrary/Queries.cs
> +        public List<string> minusQueries {set; get;} = new ();
++

2022-02-22 08:47 UTC, ARB1380 commented on searchProject_csharp/SampleLibrary/SampleLibrary/QueryManager.cs
> +        }
++

2022-02-22 08:48 UTC, ARB1380 commented on searchProject_csharp/SampleLibrary/SampleLibrary/FileReader.cs
> +        public Boolean readDataFromFile(string path,string name){
++

2022-02-23 05:51 UTC, RAAvenger approved these changes

2022-02-23 08:50 UTC, merged