initialize
Star-Academy/Winter1400-Co_Op pull request #8
Opened 2022-02-22 11:20 UTC by mohammadKhalafi

2022-02-23 06:05 UTC, MKasaei00 requested changes

2022-02-23 06:05 UTC, MKasaei00 commented on csharpProject_efcore/app/console-app/Program.cs
> +new Controller().Run(studentsPath : "../../../../files/students.txt",
طول خط زیاد است
با استفاده از متغییرها کد رو تمیز کنین

2022-02-23 06:05 UTC, MKasaei00 commented on csharpProject_efcore/app/library/controllers/DatabaseManager.cs
> +            .Take(3)
این عدد رو به عنوان ورودی از تابع بگیرین و تابع عام منظوره بزنین

2022-02-23 06:05 UTC, MKasaei00 commented on csharpProject_efcore/app/library/controllers/DatabaseManager.cs
> +            .Select(x => $"{x.name} {x.score}")
single responsiblity

اول یه لیستی از تاپل نام و نمره تولید کنین بعد با یه تابع دیگه به صورت رشته دربیارین

2022-02-24 11:34 UTC, RAAvenger approved these changes
خسته نباشید

2022-02-24 11:34 UTC, RAAvenger commented on csharpProject_efcore/app/console-app/Program.cs
> +    new DatabaseInitializer(), new DatabaseQueryForFindingANumberOfBestAverages(3)).Run();
https://docs.microsoft.com/en-us/visualstudio/ide/reference/wrap-indent-align-refactorings?view=vs-2022#wrap-indent-and-align-parameters-or-arguments

indent wrapped parameters

2022-02-24 11:34 UTC, RAAvenger commented on csharpProject_efcore/app/console-app/Program.cs
> +    new DatabaseInitializer(), new DatabaseQueryForFindingANumberOfBestAverages(3)).Run();
https://docs.microsoft.com/en-us/visualstudio/ide/reference/wrap-indent-align-refactorings?view=vs-2022#wrap-indent-and-align-parameters-or-arguments

indent wrapped parameters

2022-02-24 11:34 UTC, RAAvenger commented on csharpProject_efcore/app/library/controllers/DatabaseQueryForFindingANumberOfBestAverages.cs
> +            .Select(x => (x.name, x.score)).ToList();
مدل شکستن کدتون یکم مشکل داره
```csharp
a.b
    .c
    .d
    .e;

hello( a,
    b,
    c,
    d);
```

2022-02-26 06:18 UTC, MKasaei00 approved these changes
خسته نباشین

2022-02-26 06:44 UTC, merged